#version: '3.8'
services:
    ueransim:
        container_name: ueransim
        image: ueransim:latest
        privileged: true
        environment:
            # GNB Congig Parameters
            - GNB_NAME="gnb_1"
            - MCC=208
            - MNC=95
            - NCI=0x000000011
            - TAC=0xa000
            - LINK_IP=192.168.70.152
            - NGAP_IP=192.168.70.152
            - GTP_IP=192.168.70.152
            - NGAP_PEER_IP=192.168.70.138
            - SST=1
            - SD=1
            - SST_0=1
            - SD_0=1
            - SST_1=1
            - SD_1=1
            - SST_2=1
            - SD_2=1
            - IGNORE_STREAM_IDS=true
            # UE Config Parameters
            - NUMBER_OF_UE=1
            - IMSI=208950000000035
            - KEY=0C0A34601D4F07677303652C0462535B
            - OP=63bfa50ee6523365ff14c1f45f88737d
            - OP_TYPE=OPC
            - AMF_VALUE=8000
            - IMEI=356938035643803
            - IMEI_SV=0035609204079514
            - GNB_IP_ADDRESS=192.168.70.152
            - PDU_TYPE=IPv4
            - APN=default
            - SST_R=1 #Requested N-SSAI
            - SD_R=1
            - SST_C=1
            - SD_C=1
            - SST_D=1
            - SD_D=1
        networks:
            public_net:
                ipv4_address: 192.168.70.152
        healthcheck:
            test: /bin/bash -c "ifconfig uesimtun0"
            interval: 10s
            timeout: 5s
            retries: 5
    ueransim2:
        container_name: ueransim2
        image: ueransim:latest
        privileged: true
        environment:
            # GNB Congig Parameters
            - MCC=208
            - MNC=95
            - NCI=0x000000010
            - TAC=0xa000
            - LINK_IP=192.168.70.153
            - NGAP_IP=192.168.70.153
            - GTP_IP=192.168.70.153
            - NGAP_PEER_IP=192.168.70.138
            - SST=1
            - SD=1
            - SST_0=1
            - SD_0=1
            - SST_1=1
            - SD_1=0
            - SST_2=1
            - SD_2=1
            - IGNORE_STREAM_IDS=true
            # UE Config Parameters
            - NUMBER_OF_UE=1
            - IMSI=208950000000036
            - KEY=0C0A34601D4F07677303652C0462535B
            - OP=63bfa50ee6523365ff14c1f45f88737d
            - OP_TYPE=OPC
            - AMF_VALUE=8000
            - IMEI=356938035643804
            - IMEI_SV=0035609204079515
            - GNB_IP_ADDRESS=192.168.70.153
            - PDU_TYPE=IPv4
            - APN=oai
            - SST_R=1 #Requested N-SSAI
            - SD_R=1
            - SST_C=1 
            - SD_C=1
            - SST_D=1
            - SD_D=1
        networks:
            public_net:
                ipv4_address: 192.168.70.153
        healthcheck:
            test: /bin/bash -c "ifconfig uesimtun0"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim:
        container_name: gnbsim
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=5
            - TAC=0x00a000
            - SST=1
            - SD=000001
            - PagingDRX=v32
            - RANUENGAPID=0 
            - IMEISV=35609204079514
            - MSIN=0000000037
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=oai.ipv4
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.138
            - GTPuLocalAddr=192.168.70.156
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.156
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
    gnbsim2:
        container_name: gnbsim2
        image: gnbsim:latest
        privileged: true
        environment:
            - MCC=208
            - MNC=95
            - GNBID=6
            - TAC=0x00a000
            - SST=1
            - SD=000001
            - PagingDRX=v32
            - RANUENGAPID=0 
            - IMEISV=35609204079514
            - MSIN=0000000038
            - RoutingIndicator=1234
            - ProtectionScheme=null
            - KEY=0C0A34601D4F07677303652C0462535B
            - OPc=63bfa50ee6523365ff14c1f45f88737d
            - DNN=oai.ipv4
            - URL=http://www.asnt.org:8080/
            - NRCellID=1
            - USE_FQDN=no
            - NGAPPeerAddr=192.168.70.138
            - GTPuLocalAddr=192.168.70.157
            - GTPuIFname=eth0
        networks:
            public_net:
                ipv4_address: 192.168.70.157
        healthcheck:
            test: /bin/bash -c "ip address show dev gtp-gnb"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    public_net:
        name: oai-cn5g-public-net
        external: true
